[package]
name = "learn-redis-with-rust"
version = "0.1.0"
authors = ["Mehmet Sefa BalÄ±k <sefa.balik@trendyol.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
